package Interfaces;


import java.sql.Connection;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.sql.SQLException;
/**
 *
 * @author andre
 */
public class MenuPrincipal extends javax.swing.JFrame {
    Connection conn;
    String nome;
    boolean isMin;
    /**
     * Creates new form MenuPrincipal
     */
    public MenuPrincipal(Connection conn, String nome, boolean isMin) {
        this.conn = conn;
        this.isMin = isMin;
        this.nome = nome;
        initComponents();
        nameDisplay.setText("Miistrante: "+nome);
        if(!isMin){
            registrarAtividadeButton.setVisible(false);
            registrarMembroButton.setVisible(false);
            registrarHorasButton.setVisible(false);
            nameDisplay.setText("Membro: "+nome);
        }
        
        //Fecha conexão com o BD após fechar janela
        addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosing(WindowEvent e) {
                try{
                    conn.close();
                    System.out.println("Conexao encerrada");
                }catch(SQLException ex) {/*Não faz nada*/}
            }
        });
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        logo = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        registrarAtividadeButton = new javax.swing.JButton();
        registrarHorasButton = new javax.swing.JButton();
        registrarMembroButton = new javax.swing.JButton();
        gerarCertificadoButton = new javax.swing.JButton();
        ConsultarHorasButton = new javax.swing.JButton();
        nameDisplay = new javax.swing.JLabel();
        logoffButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interfaces/Images/logoUTF.png"))); // NOI18N

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        registrarAtividadeButton.setText("Registrar atividade");
        registrarAtividadeButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                registrarAtividadeButtonMouseClicked(evt);
            }
        });

        registrarHorasButton.setText("Registrar horas");
        registrarHorasButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                registrarHorasButtonMouseClicked(evt);
            }
        });

        registrarMembroButton.setLabel("Registrar membro");
        registrarMembroButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                registrarMembroButtonMouseClicked(evt);
            }
        });

        gerarCertificadoButton.setText("Gerar certificado");
        gerarCertificadoButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                gerarCertificadoButtonMouseClicked(evt);
            }
        });

        ConsultarHorasButton.setText("Consultar horas");
        ConsultarHorasButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ConsultarHorasButtonMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(registrarAtividadeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 88, Short.MAX_VALUE)
                        .addComponent(registrarHorasButton, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(registrarMembroButton, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(ConsultarHorasButton, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(gerarCertificadoButton, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(26, 26, 26))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ConsultarHorasButton)
                    .addComponent(gerarCertificadoButton))
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(registrarAtividadeButton)
                    .addComponent(registrarHorasButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addComponent(registrarMembroButton)
                .addContainerGap())
        );

        nameDisplay.setText("Ministrante:");

        logoffButton.setText("Sair");
        logoffButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoffButtonMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(103, 103, 103)
                .addComponent(logo, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(59, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(logoffButton)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(nameDisplay)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(43, 43, 43))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(logo)
                .addGap(14, 14, 14)
                .addComponent(nameDisplay)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(logoffButton)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void registrarAtividadeButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_registrarAtividadeButtonMouseClicked
        RegistrarAtividades r = new RegistrarAtividades(this.conn, this.nome, isMin);
        r.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_registrarAtividadeButtonMouseClicked

    private void logoffButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoffButtonMouseClicked
        TelaLogin t = new TelaLogin(this.conn);
        t.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_logoffButtonMouseClicked

    private void registrarMembroButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_registrarMembroButtonMouseClicked
       RegistrarMembros r = new RegistrarMembros(this.conn, this.nome, isMin);
        r.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_registrarMembroButtonMouseClicked

    private void registrarHorasButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_registrarHorasButtonMouseClicked
        RegistrarHoras r = new RegistrarHoras(this.conn, this.nome, isMin);
        r.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_registrarHorasButtonMouseClicked

    private void gerarCertificadoButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_gerarCertificadoButtonMouseClicked
        GerarCertificado g = new GerarCertificado(this.conn, this.nome, isMin);
        g.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_gerarCertificadoButtonMouseClicked

    private void ConsultarHorasButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ConsultarHorasButtonMouseClicked
        ConsultarHoras c = new ConsultarHoras(this.conn, this.nome, isMin);
        c.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_ConsultarHorasButtonMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ConsultarHorasButton;
    private javax.swing.JButton gerarCertificadoButton;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel logo;
    private javax.swing.JButton logoffButton;
    private javax.swing.JLabel nameDisplay;
    private javax.swing.JButton registrarAtividadeButton;
    private javax.swing.JButton registrarHorasButton;
    private javax.swing.JButton registrarMembroButton;
    // End of variables declaration//GEN-END:variables
}
