package Interfaces;

import java.sql.*;
import javax.swing.JOptionPane;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;


public class RegistrarAtividades extends javax.swing.JFrame {

    Connection conn;
    String n;
    boolean isMin;
    
    public RegistrarAtividades(Connection conn, String n, boolean isMin) {
        this.isMin = isMin;
        this.conn = conn;
        this.n = n;
        initComponents();
        
        //Fecha conexão com o BD após fechar janela
        addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosing(WindowEvent e) {
                try{
                    conn.close();
                    System.out.println("Conexao encerrada");
                }catch(SQLException ex) {/*Não faz nada*/}
            }
        });
    }
  


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LogoUTF = new javax.swing.JLabel();
        nomeText = new javax.swing.JLabel();
        numIDText1 = new javax.swing.JLabel();
        numID = new javax.swing.JTextField();
        nomeAti = new javax.swing.JTextField();
        botaoConfirmar = new javax.swing.JButton();
        botaoVoltar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        LogoUTF.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interfaces/Images/logoUTF.png"))); // NOI18N

        nomeText.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        nomeText.setText("Nome da atividade");

        numIDText1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        numIDText1.setText("Número de identificação");

        numID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numIDActionPerformed(evt);
            }
        });

        botaoConfirmar.setText("Confirmar");
        botaoConfirmar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botaoConfirmarMouseClicked(evt);
            }
        });

        botaoVoltar.setText("voltar");
        botaoVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoVoltarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(63, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(numIDText1)
                    .addComponent(nomeText)
                    .addComponent(LogoUTF, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(numID)
                    .addComponent(nomeAti)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(botaoVoltar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(botaoConfirmar, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(48, 48, 48))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LogoUTF)
                .addGap(60, 60, 60)
                .addComponent(numIDText1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(numID, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(nomeText)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(nomeAti, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botaoConfirmar, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                    .addComponent(botaoVoltar))
                .addGap(12, 12, 12))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void numIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_numIDActionPerformed

    private void botaoConfirmarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaoConfirmarMouseClicked
        // TODO add your handling code here:
        String id = numID.getText();
        String nome = nomeAti.getText();
        try{
            PreparedStatement st = conn.prepareStatement("CALL registrarAfazer("+id+", "+"'"+nome+"')");
            st.execute();
            JOptionPane.showMessageDialog(null, "Atividade registrada com sucesso!!!");
        }catch(SQLException e){
            if(e instanceof SQLIntegrityConstraintViolationException){
                JOptionPane.showMessageDialog(null, "Atividade já existe!!!");
            }
            System.err.println("Ocorreu um erro!!!");
            JOptionPane.showMessageDialog(null, "Ocorreu um erro!!!");
        }
        
    }//GEN-LAST:event_botaoConfirmarMouseClicked

    private void botaoVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoVoltarActionPerformed
        MenuPrincipal m = new MenuPrincipal(this.conn, this.n, isMin);
        m.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_botaoVoltarActionPerformed
   
    
    /**
     * @param args the command line arguments
     */
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LogoUTF;
    private javax.swing.JButton botaoConfirmar;
    private javax.swing.JButton botaoVoltar;
    private javax.swing.JTextField nomeAti;
    private javax.swing.JLabel nomeText;
    private javax.swing.JTextField numID;
    private javax.swing.JLabel numIDText1;
    // End of variables declaration//GEN-END:variables
}

